### PR TITLE
feat: support generic oauth2

### PR DESCRIPTION
**Pull request by decentral1se**
Hi following https://github.com/janeczku/calibre-web/issues/2199 I've been looking into the feasability of meeting a compromise between 1. not wanting to add additional login methods and 2. supporting a broader set of oauth2 providers.

My solution for this has been to implement a "generic" oauth2 provider which can support anything that supports oauth2. This would mean that you could potentially deprecate Github/Google methods and use this Generic method as the one oauth2 implementation. All sorts of oauth2 providers can then be supported without further coding work.

I don't think my implementation is very good but it is a start and it does indeed work. I'm testing it now. I don't know how to support migrations so this breaks when running with existing installations.

Curious if this can be merged in some fashion or if there is space for more discussion?

### CODE REVIEW

**Comment by rscmbbng** [comment]
Oh nice @decentral1se, this is an incredibly useful feature. I understand you are still building it out so here some comments after using this feature:

* "Default Settings for New Users " (set in `/admin/viewconfig`) are not applied to users logging in for the first time via the generic oauth

* In case admins only allow login via generic oauth, a toggle where calibre-web's native login is hidden (or a mapping of the login button directly to `/link/generic`) would be handy

* In theory one could inherit different roles from the OAuth provider, for example whether someone is an administrator or has particular permissions. That could be useful to support.  

* Generic oauth login currently allows only a singular 'generic' login, but one could easily imagine more would be configured.

**Comment by Northguy** [comment]
+1 

I would appreciate implementation of a generic Oauth. Would fit perfectly with my reverse proxy and Authelia

**Comment by decentral1se** [comment]
Thanks for feedback! More most welcome. I am maintaining a temporary fork with this patch over in https://git.coopcloud.tech/coop-cloud-chaos-patchs/calibre-web and have published the `thecoopcloud/calibre-web` docker image via https://git.coopcloud.tech/coop-cloud-chaos-patchs/docker-calibre-web. So, you can already test this if you want! A group is already testing https://books.lumbung.space now and things are doing fine I think. Configs for the deployment in https://git.coopcloud.tech/coop-cloud/calibre-web also. Curious if more people find this feature useful.

**Review by kelvinalfaro — APPROVED** [review]

**Comment by OzzieIsaacs** [comment]
Sorry guys. 
I stick to my opinion that I will not include any more oauth provider or any other login routine. I don't use this and it's heavy for me to support and this type of feature create a lot of problems as errors are hard to reproduce and I don't want to end up programming administration routines instead of programming a ebook online presenting app.

**Comment by decentral1se** [comment]
@OzzieIsaacs can't we just remove Google/Github and use this instead? So, instead of 3 login routines, you have 1. The code in this PR supports anything that speaks OpenID Connect. I really don't want to maintain a fork...

**Comment by OzzieIsaacs** [comment]
Sorry guys, I stick to my opinion. 
From the past I know that only a very small minority is using OAuth. Compared to this many times people show up and want 
OAuth login for this and that provider. From reverse proxy use cases I know that many people with small "admin" knowledge try to set up complex things, which causes frequently trouble. 
I don't want to spend time to support this, spending hours to set up certain OAuth provider and figure out how to set it up with user who tell my only a little amount of what they did and how their installation looks like

**Comment by RXWatcher** [comment]
I really don't understand your mentality on this. Many people have asked for this and now we even have a PR for it. It feels like you're being stubborn just for the sake of being stubborn. People could work up wiki examples and contribute to make this easy for people to understand. I get that you do not want additional work supporting this. I get that very clearly. I wouldnt want additional work for you. I do think you need to be open however that you're not everyone. If someone has actually taken the time to write a PR that just makes the current implementation universal then why do you immediately have he say no? There are enough people who want this that your simply saying no without really looking at logically is really demeaning to your users. I feel like a child on this topic. "Daddy, look what I drew..can I please hang it on the wall?" "No, I like my walls the way they are" without even considering the wants or needs of the child. Can you please take another look and be open minded about it? If you put up a poll then you'd get peoples opinion on this.

**Comment by Pfuenzle** [comment]
@OzzieIsaacs 
I strongly agree with @RXWatcher, it would be great if you would reconsider your decision.
You have Google and GitHub as an OAuth option, so having one more should not be that big of a deal, especially as it's such an advantage for users/admins.

Your point that not many people use it is fair, but with only Google and GitHub the choice is fairly limited which also decreases the userbase, having this universal method allows all OAuth providers to work, even self hosted ones, so more people can and will use OAuth. The most work has been done with this commit, you mostly just have to merge it and done. 

That you don't want to deal with supporting users failing to implement generic OAuth is also understandable, but from my experience looking into other projects that implemented generic OAuth (even similar projects like Komga, a selfhosted Web Manga Library), such issues or support requests are almost nonexistent or very fast resolved by the community. 

This is probably because most if not all people selfhosting a service, especially when selfhosting an OAuth Provider, have enough experience to figure out potential OAuth configuration issues by themselves, as there is a lot of documentation from Google and GitHub, so I don't really think support would be much of an issue.

For the effort needed to keep this up to date, I'm not 100% sure, but from what I know this implementation would not be needed to be updated as OAuth has been pretty consistent in the past, but even if updates would be needed sometime in the future, I'm sure this would be handled by members of the community by pull requests.

In the end, I think merging this pull request will increase the user count having OAuth because of more flexibility and will allow me and many more to implement their own OAuth Flows (which will make us happy :) ), while only increasing the support amount for this feature by a minimal amount (if even any).

It would be very great if you would reconsider your decision to implement this feature.
Thanks a lot

**Comment by joshumax** [comment]
Sorry to bump a closed issue, but it is really unfortunate that in order to work with University SSO for the Computer Science department where I studied, I have to maintain a fork of calibre-web because the two default providers have absolutely no 
customizability. I really hope you reconsider your stance on this @OzzieIsaacs - I'd even offer to maintain that specific bit of code.

**Comment by RXWatcher** [comment]
Id even donate like 100 euros directly for this if he'd actually integrate it.

**Comment by decentral1se** [comment]
If anyone wants to co-maintain the SSO fork & keep up with upstream, I'd gladly join forces. Hit Me Up.

**Comment by OzzieIsaacs** [comment]
The current implementation is way to complex for users, I'm fearing a lot of questions regarding what to fill out here and there and so on.
What we could do:
In the code we still support github and google (with the generic procedure). Additionally create a file where the users can add additional oauth providers with all the needed config options (name, callback routine and so on..), just leaving the variable ones open to the user (private and public key). I think one in all line would be good. Maybe csv format?, or a yaml format (at least something users can handle and easily read) In the UI the name of the oauth provider is showing up and if you select it you can fill in the additional config options (public and private key). Furthermore please find a solution for the logo showing up in the old implementation on the login screen. (Some place where the users can place the files and they are getting read by calibre-web and displayed on the login screen.
Please create the pull request to the development branch (should be more or less even with the main branch)  
Please also generate a entry in the wiki to describe what to enter in the file, where to find it. Users than could also extent the entry in the wiki with their working configs.
With this complicated procedure I'm no longer feeling forced to support the users with their config options. And the users with very very limited knowledge hopefully never try to extend it and won't generate support work.    
Last thing: I request some testing routines (mostly focused on wrong file format, non writeable files and so on: (https://github.com/OzzieIsaacs/calibre-web-test/tree/development/test)

**Comment by decentral1se** [comment]
Looks like we're back in the game folks :upside_down_face: 

To summarise what you wrote @OzzieIsaacs so as to confirm I understand clearly:

- i should aim to deprecate/remove the existing oauth implementation
- and replace it with the generic implementation to support oauth login
- add an additional file based logic to support adding additional providers
- add support for image upload for login buttons
- submit these changes to the dev branch
- write a wiki page which clearly explains all the oauth form fields

Is that correct?

Also one question: can we re-use your existing database implementation of the oauth provider instead of the file based approach? I can't see the benefit of the file based approach & avoiding it would be less work. Then the form simply iterates through databse objects instead of files.

And my response in general: you're asking for a lot of new work. You are also coming from a position of rejecting the work to accepting the work without a clear statement. So, before I take the risk of starting this, can you please confirm that you are going to follow through with accepting this work if it matches your expectations? I agree to work to your expectations but you must merge the PR then. I don't want to waste my time.

**Comment by OzzieIsaacs** [comment]
> i should aim to deprecate/remove the existing oauth implementation

Yes, it makes no sense to have a generic implementation and an additional implementation for 2 simple "instances of the generic one

> add an additional file based logic to support adding additional providers

The file based logic shall be some sort of config file for additional providers, to avoid having a lot of config options visible in the UI I expect less support requests if there is no "visible" extension possibility in the UI. This is still my main concern having a lot of people asking for support for oauth providers you never heared of.

> add support for image upload for login buttons

The images don't have to be uploadable. Load them from a folder on the server, name could be given in the config file mentioned above. Or the name has to be the name of the oauth provider.

> Also one question: can we re-use your existing database implementation of the oauth provider instead of the file based approach? 

The data from the config file can be copied to the database and read during normal operation from there. Only one config file would be needed not one file for each provider.

> You are also coming from a position of rejecting the work to accepting the work without a clear statement

My main concern is not the maintenance of the code, it's the support by people asked. By using a config file my hope is that people would describe working config options in the wiki and I'm feeling not forced to help people setup their oauth workflow if it's not accessible via the UI. Having an UI with the current options from this PR will in my opinion generate a lot of questions.

> I agree to work to your expectations but you must merge the PR then. I don't want to waste my time.
Yes I will merge it, otherwise I would just not have responded, as I already closed the PR.

**Comment by Jafner** [comment]
@OzzieIsaacs This feature would be hugely useful to me and I would be happy to work with @decentral1se to build documentation for the feature if that tips the scales at all.

**Comment by Jafner** [comment]
@decentral1se,
@ace-archer and I have begun work on a fork for this here: https://gitlab.jafner.net/Jafner/calibre-web  

I've pulled the latest upstream ([07c67b0](https://github.com/janeczku/calibre-web/commit/07c67b09dbea50f7bcc7a85ac4a5b495128f6091)) and applied your patch ([0e5548e](https://github.com/decentral1se/calibre-web/commit/0e5548e90fe1c98be44bdb7545d0f19f805d6d87)) on top of it. At this point, the application works (as visible here: https://books.lumbung.space/login?next=%2Fme).  

My environment uses [Authentik](https://goauthentik.io/) rather than Keycloak, and this initial implementation has some hardcoded values specific to Keycloak (such as the relative userinfo path). So Ace-Archer and I are working to build out an implementation of this feature that works.  

If you're open to it, we would really appreciate a chance to chat with you about making this work, as we're diving in blind and your insight would likely alleviate some frustration in the early stages.

**Comment by decentral1se** [comment]
Hey @Jafner I didn't get back around to this but it is on my TODO stack... I will be travelling for a while now but if you want to reach me, drop a mail via `d34ae261d3 at sinenomine dot email` with questions, can try to answer. Otherwise, I'll try to get back on this shortly and we could combine our powers.

**Comment by decentral1se** [comment]
@Jafner and myself have been chatting via mail, we're kicking off a matrix chat to organise around this work and coordinate. Please join in if you want to chat! It's an open room for all calibre-web contributors, however you contribute, with code, design, discussion, etc. Link:

> https://matrix.to/#/#calibre-web-contrib:autonomic.zone

**Comment by RXWatcher** [comment]
You just made my month! Thank you for being open to this.

**Comment by decentral1se** [comment]
Still would like to pick this up one day but budget became an issue in the related project and it is stalled for now.

I'll close this off for now and maybe I'll come back to it! If anyone wants to pick up this work, please do.

**Comment by ajn142** [comment]
> @decentral1se, @ace-archer and I have begun work on a fork for this here: https://gitlab.jafner.net/Jafner/calibre-web
> 
> I've pulled the latest upstream ([07c67b0](https://github.com/janeczku/calibre-web/commit/07c67b09dbea50f7bcc7a85ac4a5b495128f6091)) and applied your patch ([0e5548e](https://github.com/decentral1se/calibre-web/commit/0e5548e90fe1c98be44bdb7545d0f19f805d6d87)) on top of it. At this point, the application works (as visible here: https://books.lumbung.space/login?next=%2Fme (note: not my instance, nor my fork, but uses Calibre-web with generic OAuth via Keycloak)).
> 
> My environment uses [Authentik](https://goauthentik.io/) rather than Keycloak, and this initial implementation has some hardcoded values specific to Keycloak (such as the relative userinfo path). So Ace-Archer and I are working to build out an implementation of this feature that works.
> 
> If you're open to it, we would really appreciate a chance to chat with you about making this work, as we're diving in blind and your insight would likely alleviate some frustration in the early stages.

@Jafner any chance you have that code somewhere else, getting a 404 on that gitlab instance, and I’m interested in contributing.

**Comment by Jafner** [comment]
Migrated over to Gitea. 
https://gitea.jafner.tools/Jafner/calibre-web

**Comment by danieljkemp** [comment]
To reiterate, adding generic oauth2 support isn't a new feature. The auth library used for GitHub and Google auth also supports OIDC. 

Oauth2/OIDC could actually be consolidated to one config page that supports GitHub/Google/generic without changing or adding auth libraries

**Comment by zchrykng** [comment]
Is anyone still working on this? I've had endless problems attempting to get the reverse proxy authentication system working and don't want to use LDAP as it is far more complex. I'm using authentik.

**Comment by danieljkemp** [comment]
No, the developer who had opened this issue ran out of cycles and closed it a good while ago. Not sure if it could be revived or would require too much of a rebase.

@OzzieIsaacs is still against supporting OIDC that isn't google or github. (see: https://github.com/janeczku/calibre-web/issues/2965) so you'd have to convince enough devs that it is worthwhile.

It *should* be possible to setup proxy auth using your OIDC system *IF* you happen to be using one of the comnbinations listed [here](https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy). If you're using some other reverse proxy it still might be possible but godspeed. There are so many possible gremlins there that I struggle to see how it is a cleaner or easier to support the reverse proxy header auth solution as opposed to just specifying the OIDC .well-known/endpoints + client/secret. Actually... how many header auth systems aren't actually just OIDC anyway? is there a significant amount of ways of providering header auth that aren't OIDC/Oauth2-based? Really? And is managing reverse proxy headers easier?

If you want to suffer, I mean give it a shot maybe oauth2-proxy could be used?

**Comment by ajn142** [comment]
> Is anyone still working on this? I've had endless problems attempting to get the reverse proxy authentication system working and don't want to use LDAP as it is far more complex. I'm using authentik.

I abandoned the efforts in my fork, as I didn’t have the skills to keep merging changes in. That said, I’m also using Authentik and have moved happily to reverse proxy auth, maybe I can help you troubleshoot that in the authentik or calibre-web discords?

**Comment by ajn142** [comment]
@zchrykng understood, I’m not a huge fan of Discord for FOSS projects in principle either, but 🤷‍♂️ more than I can change. Feel free to try picking up from my fork, it has working generic OIDC (thanks @decentral1se and @Jafner) but is behind current calibre-web by a good bit. I’ll also see if I can find my conversation with Ozzie on the topic, he laid out some pretty clear goals on what we’d have to meet for him to even consider merging it in (offhand, not breaking things and not adding to his support burden, much like the details he provided in the thread above).

If that doesn’t work out, the offer stands on helping RE header auth.

**Comment by zchrykng** [comment]
@ajn142: Thanks! Really do appreciate the offer.

My initial take are that these would be the three key points,

1. Don't break existing installs - Auto migrate existing setups to the new data structure
2. Rework the UI to allow entering all the OAuth values that are currently hidden
3. Provide buttons for the existing OAuth login options that pre-fills the form with the known values?

**Comment by gelbphoenix** [comment]
@OzzieIsaacs: Would it be a support burden if we follow up with the original plan (remove specific OIDC providers, adding a generic option) if we transfer the existing OIDC configs of instances and write an wiki explaination entry for new instaces and their admins?

**Pull request closed without merging**
