### PR TITLE
Remove "Delete selections" for checkbox in table

### PR DESCRIPTION
**Pull request by photonq2**
Button unnecessary. Checkbox in tables already there.

image
image

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
With this change it's one click more to deselect everything. The first click selects all elements on the page and the second one is deselecting everything. I agree that this is a more usual way of selecting things in a table.
I have to think on this

**Comment by photonq2** [comment]
Keep in mind future bulk edit/delete buttons

**Comment by webysther** [comment]
Remove 30 books some days ago...

**Comment by OzzieIsaacs** [comment]
I meanwhile had time to look at the commit. Meanwhile with the current implementation it's possible to select books (books table) on different pages (at least until you reload the page). Your commit does break this.
In the background the javascript keeps a list of ticked books, to do it for all books an additional request for getting all "currently visible" books to tick them. I currently don't think the effort for making this possible doesn't match with the benefit for it, so I would close the PR. Sorry for the long waiting time

**Pull request closed without merging**
