### PR TITLE
Fix for #33, #28, #23

### PR DESCRIPTION
**Pull request by OzzieIsaacs**
App.db has to be deleted after appliing the changes

Includes:
- Bugfix for feeds
- Translation of UI
- login page is free of non accessible elements
- boolean custom column is vivible in UI
- books with only with certain languages can shown
- book shelfs can be deleted from UI

### CODE REVIEW

**Comment by cervinko** [comment]
i get this error:
`127.0.0.1 - - [08/Aug/2016 23:27:56] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/calibre-web/vendor/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/calibre-web/cps/web.py", line 68, in __call__
    return self.app(environ, start_response)
  File "/home/calibre-web/vendor/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/calibre-web/vendor/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/calibre-web/vendor/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/calibre-web/vendor/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/calibre-web/vendor/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/calibre-web/vendor/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/calibre-web/vendor/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/home/calibre-web/cps/web.py", line 270, in before_request
    g.public_shelfes = ub.session.query(ub.Shelf).filter(ub.Shelf.is_public == 1).all()
  File "/home/calibre-web/vendor/sqlalchemy/orm/query.py", line 2241, in all
    return list(self)
  File "/home/calibre-web/vendor/sqlalchemy/orm/query.py", line 2353, in __iter__
    return self._execute_and_instances(context)
  File "/home/calibre-web/vendor/sqlalchemy/orm/query.py", line 2368, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/calibre-web/vendor/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/home/calibre-web/vendor/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/calibre-web/vendor/sqlalchemy/engine/base.py", line 828, in _execute_context
    None, None)
  File "/home/calibre-web/vendor/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/home/calibre-web/vendor/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/calibre-web/vendor/sqlalchemy/engine/base.py", line 824, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/home/calibre-web/vendor/sqlalchemy/engine/default.py", line 442, in _init_compiled
    self.cursor = self.create_cursor()
  File "/home/calibre-web/vendor/sqlalchemy/engine/default.py", line 605, in create_cursor
    return self._dbapi_connection.cursor()
  File "/home/calibre-web/vendor/sqlalchemy/pool.py", line 491, in cursor
    return self.connection.cursor(*args, **kwargs)
ProgrammingError: (ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140090641282816 and this is thread id 140090471290624 'SELECT shelf.id AS shelf_id, shelf.name AS shelf_name, shelf.is_public AS shelf_is_public, shelf.user_id AS shelf_user_id \nFROM shelf \nWHERE shelf.is_public = ?' [immutabledict({})]
`

**Comment by cervinko** [comment]
perhaps i made a mistake at merging. i pushed my merged version here: https://github.com/cervinko/calibre-web/tree/OzzieIsaacs-develop

**Comment by OzzieIsaacs** [comment]
Yes, no merging error. I never tried it with debug switch activated. If you use in normal mode than it is working. The error occours only in debug mode. But we can not leave it that way, i will have a deeper look into it, but it looks complicated.

**Comment by cervinko** [comment]
this is fixed in https://github.com/cervinko/calibre-web/pull/1

**Comment by cervinko** [comment]
@OzzieIsaacs i think if we start to make the left menu customizable (removing random book) we should prepare the db for all menu entries to be customizable. f.e for my usecase 'language' and 'author' is quite useless.

**Comment by OzzieIsaacs** [comment]
Sounds like a good dies to me. I was thinking about something like customized searches which could be displayed in the left menu. This could be a generis approach, nie there is much redundant Code in displaying the diffrent menu entries. But up to now i am not further into it as this.

**Comment by OzzieIsaacs** [comment]
Dies= idea (auto correction)
Generis= generic 
Nie = now

**Pull request closed without merging**
