### PR TITLE
Simple thumbs

### PR DESCRIPTION
**Pull request by dncpax**

### CODE REVIEW

**Comment by dncpax** [comment]
I'm so sorry for the noise. I'd delete this if I knew how...

**Comment by AnonTester** [comment]
@dncpax what's happening with this PR? 
This is a great idea and I noticed the thumb size issue as well. 10mb or higher page size is too much, especially on ebook browsers, so some form of resizing has to be implemented.

**Comment by OzzieIsaacs** [comment]
There is anothe pr in test currently

**Comment by dncpax** [comment]
@AnonTester  I’ve fumbled GitHub so bad I started over:
https://github.com/dncpax/calibre-web

The only difference is in helpers.py.

I didn’t make a pr bc I saw there had been a much larger effort in another pr and did not think my small changes were good enough.

Hope @OzzieIsaacs releases his pr.

**Pull request closed without merging**
