### PR TITLE
Minor code clean-ups

### PR DESCRIPTION
**Pull request by pwr**
Entirely optional. Comments welcome.

BTW. In cps.py, isn't `sys.path[0]` always be the same as `os.path.dirname(os.path.abspath(__file__))` ? In all my tests, it has been. Is there a situation when it is not?

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
It's absolutly possible that it's the same. I changed it 2 years ago (or so). My python knowledge is more general and I don't know all tipps and tricks. I was solving the problem (starting the script from another working directory) the straight way, by looking for a way to find the path to the current file (looking around a way to extract it from "__FILE__") -> you could change it.

**Comment by OzzieIsaacs** [comment]
Correction: There was a reason for changing it. 
I remember changing it while working on making calibre-web on pypi hosted with a startscript

**Comment by OzzieIsaacs** [comment]
I'm currently working on it again. So maybe I can find out the problem within this week

**Comment by pwr** [comment]
Found a situation: when started as a module (-m cps), `sys.path[0]` is the current directory.

**Comment by OzzieIsaacs** [comment]
Yes, this was the problem, so we leave it as it is.

**Comment by OzzieIsaacs** [comment]
With your change hitting restart calibre-web in the admin section causes this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 923, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ooooo/Entwicklung/calibre-web/cps/reverseproxy.py", line 78, in __call__
    return self.app(environ, start_response)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ooooo/.local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ooooo/Entwicklung/calibre-web/cps/web.py", line 157, in inner
    return f(*args, **kwargs)
  File "/home/ooooo/Entwicklung/calibre-web/cps/admin.py", line 84, in shutdown
    db.dispose()
  File "/home/ooooo/Entwicklung/calibre-web/cps/db.py", line 421, in dispose
    delattr(Books, attr)
  File "/home/ooooo/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 82, in __delattr__
    _del_attribute(cls, key)
  File "/home/ooooo/.local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 817, in _del_attribute
    "Can't un-map individual mapped attributes on a mapped class."
NotImplementedError: Can't un-map individual mapped attributes on a mapped class.
2019-07-16T19:36:43Z {'REMOTE_PORT': '50232', 'HTTP_HOST': '127.0.0.1:8083', 'REMOTE_ADDR': '::ffff:127.0.0.1', (hidden keys: 26)} failed with NotImplementedError
```
Putting a try except block around it solves the problem, but then the code does nothing??

**Comment by pwr** [comment]
Odd, works for me.
What SqlAlchemy version do you have?

**Comment by OzzieIsaacs** [comment]
I tried 1.34 and 1.35 both on python 2.7 and 3.6 (Linux mint, with pycharm as debugger)

**Comment by pwr** [comment]
1.2.18 here. Alright, will upgrade and fix it.

**Pull request merged**
