### PR TITLE
Use lazy loading to show images

### PR DESCRIPTION
**Pull request by jkrehm**
Loads images when they're within 200px of being in the viewport. Prevents loading images that might not be seen, and ought to improve "time to first render" performance.

lazy-load

### CODE REVIEW

**Comment by jkrehm** [comment]
@OzzieIsaacs @janeczku any feedback on this PR?

**Comment by OzzieIsaacs** [comment]
Let me check that lazy loading doesn't yield to endless page refreshes on e-ink readers like kindle

**Comment by jkrehm** [comment]
Ah. On my Kindle Paperwhite it doesn't load the new images as you scroll down. Not sure how to debug it, but I'll see if I can figure something out.

I actually made the change primarily for my Kindle because the large number of images and their large size max out the available memory and make the browser crash. My hope is that by lazy loading I can navigate around more easily without having it crap out on me.

**Comment by jkrehm** [comment]
Unfortunately the Kindle browser doesn't report its y scroll position. )= I assume its just the lousiness of the browser, because work-arounds that are supposed to work back to IE 6 still don't work.

```
$(window).on("scroll", function() {
    alert("window.pageYOffset=" + window.pageYOffset + " window.scrollY=" + window.scrollY + " document.documentElement.scrollTop=" + document.documentElement.scrollTop + " document.body.scrollTop=" + document.body.scrollTop);
});
```

All of those return `0` when I scroll on my Paperwhite, so it's impossible to know if the images have scrolled into view. Super unfortunate.

I still think lazy loading the images are an important optimization for use with normal (non-Kindle) browsers. We could do browser detection (e.g. check if `window.navigator.userAgent` contains "Kindle" and if so load all images immediately) but it does eliminate the performance (and memory) gains of lazy loading them. Thoughts?

**Comment by cmer** [comment]
I'd personally make the lazy loading a lot more aggressive. It's quite annoying to constantly have to wait for images loading when scrolling. Perhaps preload within 1000px or so?

**Comment by jkrehm** [comment]
I'm game for that because I've also run into the hassle of images loading too slowly.

I'm not sure what to do about browsing on Kindle. I originally created the PR because loading my library on my Kindle crashed the browser (I'm guessing it's because it runs out of memory loading all of the images) but the Kindle browser is so lousy that you can't lazy load.

So, I don't know.

**Comment by cmer** [comment]
Infinite scrolling on Kindle might not be a good idea. Pagination might be better since the device has limited resources.

**Comment by OzzieIsaacs** [comment]
I'm personally happy with the speed of loading the images the way it is now, so I'm hesitating (?) to merge this PR.

**Comment by OzzieIsaacs** [comment]
I'll close this PR now. 
Thanks anyway for the cool javascript things you implemented it brought the project a big step ahead

**Pull request closed without merging**
