### PR TITLE
Audiobook support -- updated with code review

### PR DESCRIPTION
**Pull request by Mohammed90**
This build on top of #495 incorporating the review comments from the maintainers.

@OzzieIsaacs could you please test it locally or on some clean environment? I'm having issues with running it locally (pip, blah...). I'm not a Pythonista, so debugging pip issues is a bit hard for me.

### CODE REVIEW

**Comment by bodybybuddha** [comment]
There maybe a problem here.  There are two get_update_status routes in web.py:

```
calibre-web    | [2018-09-15 13:15:15,592] INFO in web: Starting Calibre Web...
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/calibre-web/app/cps.py", line 13, in <module>
calibre-web    |     from cps.server import Server
calibre-web    |   File "/calibre-web/app/cps/server.py", line 20, in <module>
calibre-web    |     import web
calibre-web    |   File "/calibre-web/app/cps/web.py", line 1147, in <module>
calibre-web    |     @login_required_if_no_ano
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1250, in decorator
calibre-web    |     self.add_url_rule(rule, endpoint, f, **options)
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 66, in wrapper_func
calibre-web    |     return f(self, *args, **kwargs)
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1221, in add_url_rule
calibre-web    |     'existing endpoint function: %s' % endpoint)
calibre-web    | AssertionError: View function mapping is overwriting an existing endpoint function: get_update_status
```

Git merging may not have been correctly?

**Comment by Mohammed90** [comment]
Sorry about that @bodybybuddha . I've removed the duplicate one in favor of the recent once. Could you try again?

**Comment by bodybybuddha** [comment]
@Mohammed90 - thanks for the fix, however, I believe a more comprehensive review will need to be done.  While I'm not a git expert, I do know there were a lot of changes (168 commits from @modembug's initial PR request) to the base code as this branch was left in a limbo state.  I'm not sure if those base code changes were correctly updated in the branch before your changes.  Somewhere along the way in this branch, we're getting "duplicate code".  

In any event - here is the error I got after your change:

```
calibre-web    | [INFO] Launching Calibre-Web ...
calibre-web    | [2018-09-15 17:32:31,227] INFO in web: Starting Calibre Web...
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/calibre-web/app/cps.py", line 13, in <module>
calibre-web    |     from cps.server import Server
calibre-web    |   File "/calibre-web/app/cps/server.py", line 20, in <module>
calibre-web    |     import web
calibre-web    |   File "/calibre-web/app/cps/web.py", line 1253, in <module>
calibre-web    |     @admin_required
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1250, in decorator
calibre-web    |     self.add_url_rule(rule, endpoint, f, **options)
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 66, in wrapper_func
calibre-web    |     return f(self, *args, **kwargs)
calibre-web    |   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1221, in add_url_rule
calibre-web    |     'existing endpoint function: %s' % endpoint)
calibre-web    | AssertionError: View function mapping is overwriting an existing endpoint function: get_updater_status
```

**Comment by modembug** [comment]
Too many changes have been made since my initial PR hence all of the conflicts. Unfortunately I do not have any time to allocate to modifying my code. Feel free to fork my branch and merge with the current code base.
________________________________

**Comment by bodybybuddha** [comment]
@modembug - thanks for the quick reply.  I'll take a stab at forking and getting the branch updated.  If I'm successful, maybe @Mohammed90 can re-add his additions to that branch.

**Comment by Mohammed90** [comment]
@bodybybuddha I can try giving you permission to push to my fork, if that would be a better approach.

**Comment by bodybybuddha** [comment]
I have the branch up to the latest code - with only 3 or 4 conflicts.  I think I have them all worked out but one?  Working on the Book Details page now - the buttons that serve up the different version is a bit off still.  Once I have that working, I'll give it a test.  

Packing it in for tonight and I'll see what I can do in the next couple of days.

**Comment by bodybybuddha** [comment]
@Mohammed90 - you may want to close out this PR.  Thanks in advance!

**Pull request closed without merging**
