### PR TITLE
Fix for #621 - Login page always in english

### PR DESCRIPTION
**Pull request by bodybybuddha**
The Guest user is configured for 'en' language by default.  The get_locale function need to include a check for this user.

Now the login page page will now render the in the browser's preferred language.  In addition, anonymous browsing will also be in the browser's preferred language.

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
Thanks for the fix. While checking it I realized one thing: IF anonymous browsing is activated the admin can set a language for the guest user, which is now no longer taken into account. I want to think a bit on it, but currently I tend to removing the language setting for the guest user, so having a consitent behavior across the guest user usecases

**Comment by bodybybuddha** [comment]
Thanks for taking a look.  

In my mind, if anonymous is activated, I would assume the administrator really doesn't care about the language the user is rendering the site in.  I think it that by not forcing a language, it gives the site more flexibility.

However, if you think it's important, we could just add a "force language" option to the config?

**Comment by OzzieIsaacs** [comment]
I‘m currently writing automatic test routines I currently feel how much work and complexity every option creates. So I decided to keep it as in your pull request.  (No need for you to merge it to the newest master commit, l‘ll do that tomorrow)

**Comment by bodybybuddha** [comment]
Cool!  I was just going through all my branches and making sure they were all up to date with the master branch, hence the update.

**Pull request merged**
