### PR TITLE
Update layout.html

### PR DESCRIPTION
**Pull request by stfrbrntyu**
Some minor visual tweaks in the top bar, so that the icons and the words have a space between them.

### CODE REVIEW

**Comment by stfrbrntyu** [comment]
I might be doing something wrong here ;)
I only wanted to commit:
https://github.com/janeczku/calibre-web/pull/996/commits/f1f91469455e71dea3164592d924ae24af6a5ce0

**Comment by OzzieIsaacs** [comment]
Shouldn't we do this via css?
In my browser it looks fine.
grafik

**Comment by stfrbrntyu** [comment]
In the layout template it is also done with a space in front of "Advanced search", so I thought also to set it in front of Tasks, Admin, admin and Logout as it looks better when there is a space between the icon and the text. But I guess it's just nitpicking. I agree with css would be better.

`<span class="hidden-sm"> {{_('Advanced Search')}}</span>`

After the change:
image

**Comment by OzzieIsaacs** [comment]
I'll remove it in front of Advanced search

**Pull request closed without merging**
