### PR TITLE
Implemented HSTS config via web frontend (fixes #1607)

### LINKED ISSUE #1607: Enabling/Disabling HTTP Strict Transport Security via web frontend
**Is your feature request related to a problem? Please describe.**
Enabling HSTS requires changing the source code;  un-commenting line https://github.com/janeczku/calibre-web/blob/1450a21d0002faa39f3c07228139113c9a7b36ed/cps/web.py#L135

**Describe the solution you'd like**
Enabling this security feature is a matter of configuration, so a checkbox in `admin/config` ("Basic Configuration -> Server Configuration") would be the correct way.

**Describe alternatives you've considered**
Alternatively one could edit the source code as described above. But depending on the method of updating this change can be overwritten by upstream changes affecting `web.py`.

**Additional context**

### PR DESCRIPTION
**Pull request by timholl**
This PR implements the feature to enable/disable HSTS without changing the source code. See #1607

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
Thanks for the fix. My idea would be more like detect the Tolino reader and deactivate the function transparent for the user, as any other browser would benefit from this feature. If you have a setting, like you implemented it, this would  lead to have it deactivated for anybody.

**Comment by timholl** [comment]
The point of HSTS is to prevent MITM attacks by enforcing encrypted connections to all clients; why should there be exceptions for certain clients? Is the Tolino reader unable to use HTTPS in general or does it just not support the HSTS header?
I would say that if someone wants to use a reader that is not capable of a certain security feature, it should simply not be enabled in the settings in the first place.

**Comment by OzzieIsaacs** [comment]
> Is the Tolino reader unable to use HTTPS in general or does it just not support the HSTS header?

Yes, it looks like Tolino reader isn't able to handle this header. This was the reason why the code was commented out

**Comment by OzzieIsaacs** [comment]
Issue for your reference: #1466

**Comment by timholl** [comment]
There are two options:

 1. Keep the global option to enable HSTS and add a label to it like „Devices which do not support this security feature (like Tolino readers) will not be able to connect.
 2. Make exceptions for those readers. This requires that those readers can be detected, like by their `User-Agent` header. Since I would not like to hardcode and maintain a list of those reader's UA headers, this should be configurable by the user. My suggestion in that case would be a user-defined regular expression.

**Comment by timholl** [comment]
Seems like this PR is now obsolet by https://github.com/janeczku/calibre-web/commit/f06cc25a990207431250197abadda101b38b8198#diff-be8c7650699ca7209b1492ab8a139f6eR135 .

> Since I would not like to hardcode and maintain a list of those reader's UA headers, this should be configurable by the user.

The now implemented solution hardcodes an exception for readers with `tolino` in their UA header.
There is no way to prevent this exception or extend it for other outdated readers (without editing the source code).

Also, HSTS headers will now be sent ever, even on non-HTTPS connections and for people without properly configured TLS certificates and local domain names, not sure which impacts this might have.

**Comment by OzzieIsaacs** [comment]
The setting was activated in an earlier version and some users of Tolino readers complained about it, nobody else ever reported an issue. 
I see this currently as a test if it causes a problem for somebody else. If somebody else has problems with this setting I consider using your suggestion. Currently I try to keep the UI as simple as possible with as less as possible settings regarding server configuration (which is hard enough)

**Comment by OzzieIsaacs** [comment]
The tolino browser seemsto be very bad implemented. I'll doublecheck the setting with my kobo reader

**Comment by OzzieIsaacs** [comment]
Sorry I got confused, the tolino problem was something else (the session "strong" stuff). I can't remember why I commented this lines out. I have to search for it, there are 2 posibility:
1) I thought it was to risky right activating it right before a release and deactivated it
2) there was a problem with something

**Comment by OzzieIsaacs** [comment]
> Also, HSTS headers will now be sent ever, even on non-HTTPS connections and for people without properly configured TLS certificates and local domain names, not sure which impacts this might have.
Mozilla pages states the following:

grafik


So it looks to me like doing it always is not so bad.

**Comment by xiazeyu** [comment]
Just some issues on my use case here.
HSTS is a good feature, while I use a mix of HTTP and HTTPS solutions on my single domain, seperated ports.
For those HTTPS sites, it works fine, but for thoese HTTP sites shared a same domain but different port, the browser will always be redirected to a non-existed HTTPS protocal. So I have to go to `chrome://net-internals/#hsts` and mannually deleted the HSTS policy everytime.

**Pull request closed without merging**
