### PR TITLE
Adding ability to send epub to Kindle

### PR DESCRIPTION
**Pull request by billouetaudrey**
Hi,

Soon, Amazon will abandoned mobi file to email.

Is it possible to add features to send epub on kindle using calibre-web ?

Thanks :)

`We would like to inform you that starting August 20, 2022, you will no longer be able to send MOBI files (.mobi, .azw) to your Kindle library. MOBI files already present in your library will not be affected by this change. MOBI is an older file format that does not support the latest Kindle features for documents. Any existing MOBI file that you wish to read with our latest document features will need to be returned in a compatible format.

Supported formats now include EPUB (.epub), you can send files in this format to your library using your Send to Kindle email address. We will also be adding EPUB format support to the free Kindle app for iOS and Android devices and the desktop Send to Kindle app for PC and Mac.

 If you have any questions, check out our help page or contact our customer service.

 Cordially,
Amazon Kindle Customer Service`

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
?
Current Master branch has the ability to send epubs to kindle. The development branch has this also merged. The latest changes from last week aren't merged to development branch, that's true. 
I'm working locally on the development branch, until this isn't pushed I can't merge the master branch again

**Comment by OzzieIsaacs** [comment]
Please update to newest nightly version

**Comment by billouetaudrey** [comment]
I need to find how to update lol

I use this docker-compose 

`---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /path/to/data:/config
      - /path/to/calibre/library:/books
      - /mnt/Elements:/mnt/Elements
    ports:
      - 8083:8083
    restart: unless-stopped

`

If you can help me :)

**Comment by mapxn** [comment]
It looks like the docker version(0.6.18) has not supported this feature.

**Comment by billouetaudrey** [comment]
You need to change to nightly ;)

My docker-compose.yml

`---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:nightly
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /path/to/data:/config
      - /path/to/calibre/library:/books
      - /mnt/Elements:/mnt/Elements
    ports:
      - 8083:8083
    restart: unless-stopped
`

**Comment by mapxn** [comment]
that's very helpful for me.
Thank you @billouetaudrey

**Comment by billouetaudrey** [comment]
> that's very helpful for me. Thank you @billouetaudrey

You are welcome :)

Sorry the docker-compose is not good typo lol

**Pull request closed without merging**
