### PR TITLE
fix the utf8 file name save to db

### PR DESCRIPTION
**Pull request by ferocknew**

### CODE REVIEW

**Comment by Kennyl** [comment]
I think  'SET LC_LOCALE="UTF-8' is better.

**Comment by Kennyl** [comment]
```
reload(sys)
sys.setdefaultencoding('utf-8')
```
are discouraged, stackoverflow contains  lots of context about this question.

If you find any unicode errors, please report again, those findings affect Python2/3 compatibility.

**Comment by OzzieIsaacs** [comment]
I agree with @kennyl.
Could you please tell us, what the exact problem is? Which path/file didn't work?

**Comment by OzzieIsaacs** [comment]
no response

**Pull request closed without merging**
