### PR TITLE
Added public /reconnect endpoint

### PR DESCRIPTION
**Pull request by yannouchou**
Should address #933

### CODE REVIEW

**Comment by yannouchou** [comment]
Hello there @OzzieIsaacs !
Any thoughts about this suggestion?

**Comment by OzzieIsaacs** [comment]
Sorry for the late reply.
I have one question: How do you think users can use this "public api"? 
Shall they enter the url in their browser and wait for an empty reply, or do you want to integrate this into some sort of srcipt? 
I think this is not very comfortable for "normal" non programming users. (Maybe better than nothing, but not comfortable)

**Comment by yannouchou** [comment]
In mind mind the idea was really mostly to support automation by scripts, typically to be executed after each new book addition in calibre.
End users already have the "reconnect" button in the UI, and for end users it's not going to be an issue to have to log in, whereas currently the requirement for being logged in makes scripting very difficult.

I have a working one-liner script but it was not that easy to figure out, only works with recent curl versions (older versions have a bug sending cookies to single-name domains), and of course requires managing and passing credentials which isn't easy to do if you really want to do it securely (and will fail with some complex password that break the form encoding):
```
curl "http://calibre-web/login" -d "username=${CALIBRE_ADMIN_USER}&password=${CALIBRE_ADMIN_PASS}&next=%2Fshutdown%3Fparameter%3D2" -L -b dummy
```

Whereas this could just be:
`curl "http://calibre-web/reconnect"`

Of course, this is not very elegant as it's still a workaround, but as you said it's probably better than nothing...

**Comment by OzzieIsaacs** [comment]
I thought a bit about it, I think it's better to trigger the reconnect at certain events (book uploaded, ..?) from inside calibre-web in case of some environment variable is set. This environment variable could be set by the docker container and so the reconnect only happens for docker users.

**Comment by yannouchou** [comment]
Hmm the problem is that many library updates happen outside of Calibre-web (e.g. from Calibre or a file sync tool). So we still need a way to externally notify Calibre-web and tell it "hey, please refresh"...
I however fully support the idea of using an env variable to enable/disable the new behaviour...

**Comment by pwr** [comment]
An endpoint is not necessary, reloading can be triggered internally by just watching `metadata.db` for changes (modification time).
But this is not quite compatible with modifying the database from within CW itself, either with uploads, metadata editing or conversions. If the file is being sync'ed externally as well, getting conflicts is just a matter of time...
Without a global configuration flag to disable all these features in Calibre-Web, sync'ing the calibre database is just unsafe.

**Comment by yannouchou** [comment]
Definitely there is no conflict-proof way of doing file syncing, but this is not the problem here.

The problem I, and I suspect many other users are facing, is simply that whenever an external update is made to the library, CW struggles to pick it up properly (e.g in my case new books will show up but not their cover image).

What I'm suggesting here with this API is definitely not a fix but a trivial workaround that I find good enough.

Continuously polling for the last file update would also work but might be an I/O overkill (in my case I know exactly when updates are made so I can trigger a reconnect just when it's needed), and I suspect not particularly easy to implement.

**Comment by benhoh** [comment]
I'm really eager for this public endpoint. My issues with needing database reconnection are exactly the same as yannouchou's — I have Calibre-Web running on from a remote Calibre database that's a mirror of my laptop's Calibre setup. For me, calibre-web is a way to access my Calibre library from a reading device when my laptop's closed. This is why having the discretion to manage this external to calibre-web would be awesome.

**Comment by Videl** [comment]
Same here, using Syncthing to synchronize the database.

**Comment by MinchinWeb** [comment]
Is this documented anywhere? I think this might be the only place with is mentioned...

**Pull request merged**
