### PR TITLE
add user-permission management

### PR DESCRIPTION
**Pull request by cervinko**

### CODE REVIEW

**Comment by janeczku** [comment]
Hey, is this ready to be merged?

**Comment by cervinko** [comment]
i think so. but i hoped that you would have a closer look at it -;)

**Comment by janeczku** [comment]
Of course!

**Comment by cervinko** [comment]
is it better now?

**Comment by janeczku** [comment]
@cervinko Just starting to review...

**Comment by janeczku** [comment]
Hi, scheint alles zu funktionieren. ANO_SHOW_BOOKS Parameter fehlt noch in der config.ini.example. Kann ich aber auch nachtragen.

**Comment by cervinko** [comment]
thx for testing and merging!

**Pull request merged**
