### PR TITLE
kobo sync: using the actual book language

### PR DESCRIPTION
**Pull request by beedaddy**
The current approach is to simply set "en" as book language. This PR tries to use the actual language specified in the metadata of the book.

### CODE REVIEW

**Comment by beedaddy** [comment]
This should fix #2512

**Comment by beedaddy** [comment]
I now realized, that the hyphenation does not work anymore for my German ebooks. The reason seams to be, that the language is set to **deu** in the content-table in KoboReader.sqlite instead of **de**…

**Comment by OzzieIsaacs** [comment]
There is a function somewhere in language.py to convert 3 letter language code to 2-letter, so no Beinbruch

**Comment by beedaddy** [comment]
Yes, I'm currently searching for such a function. I'm very new to the codebase, so … :)

**Comment by OzzieIsaacs** [comment]
I thinks it's this one:
https://github.com/janeczku/calibre-web/blob/b5d5660d04acc98283b4ff4a798596d0d270441e/cps/isoLanguages.py#L42

import isoLanguages

lancode="deu"
result = isoLanguages.get(part3=langcode).part1

(I'm not on my computer so I can't test it)

**Comment by beedaddy** [comment]
Thanks for the hint. Now it looks good here.

**Comment by beedaddy** [comment]
@OzzieIsaacs Please let me know if there's anything else missing to get this PR accepted.

**Pull request merged**
