### PR TITLE
Embed metadata on download

### PR DESCRIPTION
**Pull request by Dunrar**
This draft PR depends on #2463. It checks if a Calibre installation has been detected and embeds metadata into a book file on download, using the Calibre CLI. 

Right now, it does not work with the GDrive integration, and I'm not sure how to deal with it. I see three options:
1. Leave it incompatible
2. Embed metadata into book files before they are being uploaded to GDrive
3. Download from GDrive to `temp`, embed the metadata and then create a response with the processed file

I don't like any of them, but would probably prefer option 2, because it does not require two downloads. Would greatly appreciate feedback. Thanks.

### CODE REVIEW

**Comment by Dunrar** [comment]
@OzzieIsaacs could you have a look at this and #2497? I need advice, especially when it comes to the GDrive integration and embedding when downloading book files. Thanks!

**Comment by OzzieIsaacs** [comment]
Sorry for the very late reply. I prefer number 3 and I implemented it in the "new" metadata branch

**Comment by Dunrar** [comment]
Alright, I see. I would have really appreciated it if you would have asked me to create PRs for that branch instead of just including the code.

Should I close this, #2497 and #2463?

**Comment by OzzieIsaacs** [comment]
Please leave it open. I just created the new branch to resolve merge conflicts and work on the code, and if I have questions to have something to talk with you

**Comment by Dunrar** [comment]
Ah, okay, sorry for the rash response!

**Comment by OzzieIsaacs** [comment]
No problem, I‘m happy that you are willing to work on the PR after one year

**Comment by OzzieIsaacs** [comment]
I'm now 2 weeks on vacation. What I found so far:
- we need something to regularly delete the temp folder, otherwise the tmp folder will grow bigger and bigger over time ( I can do this after my vacation)
- if something goes wrong the error should not only be logged, there should be a user message

**Comment by OzzieIsaacs** [comment]
I finalizes my tests and merged it to the development branch. I run all tests this night, I need to add some more tests for another feature and than we are done

**Pull request merged**
