### PR TITLE
Fix bug on geting book metadata from douban

### PR DESCRIPTION
**Pull request by xxxyangyu**
Apikey is unavailable for api.douban.com now with error message "invalid_apikey, Please contact bd-team@douban.com for authorized access.".
The new API, frodo.douban.com, is designed for Douban wechat mini program. Modify the get_meta method to fit the new API.

### CODE REVIEW

**Comment by litianyu0707** [comment]
> Apikey is unavailable for api.douban.com now with error message "invalid_apikey, Please contact [bd-team@douban.com](mailto:bd-team@douban.com) for authorized access.".
> The new API, frodo.douban.com, is designed for Douban wechat mini program. Modify the get_meta method to fit the new API.

what should i do  for fix the bug, can you teach me ? thank you!

**Comment by OzzieIsaacs** [comment]
Sorry, it's not working for me: I'm getting: 
grafik
(Firefox on Linux Mint, with the newest master commit from march 15th)
I tried to search for 西游记 (Journey to the West in simplified? chinese)
grafik

**Comment by xxxyangyu** [comment]
> Sorry, it's not working for me: I'm getting:
> grafik
> (Firefox on Linux Mint, with the newest master commit from march 15th)
> I tried to search for 西游记 (Journey to the West in simplified? chinese)
> grafik

Yes, the API provider changed there policy.

**Comment by cat94** [comment]
Maybe the only problem is how to get a valid apiKey. With software like fiddler, we can obtain our personal apiKey by capturing Wechat mini program's network traffic, which works fine after replacing. 

screenshot

Btw, dbApiKey and apiKey seems redundant in this commit.

**Pull request closed without merging**
