### PR TITLE
Prefer kepub (#1439)

### PR DESCRIPTION
**Pull request by dmogle**
Only offer kepub download URL over Kobo sync API when available

### CODE REVIEW

**Comment by flying-sausages** [comment]
Would it be possible to just stop offering "fake" `kepub` items altogether? This would essentially force a user to do the manual conversion, and it would reduce a lot of the confusion on why some books don't work the way an end-user would expect them to.

**Comment by dmogle** [comment]
The Sync API is never offering "fake" kepubs, I think Kobo e-readers just assume that any epub offered by the API is internally formatted like a kepub. Some epubs seem to be, in my experience. We could only offer kepub formatted books but personally I would rather have a poorly formatted epub than nothing at all?

**Comment by flying-sausages** [comment]
I see what you're saying. It's just that the reader will always say the format is "kobo epub" instead of just "epub". But at the end of the day each book would behave differently. On the other hand, `kepubify`ed books will all behave properly with expect-able results.

I would argue that it would be better to "push" this into a direction where it works flawlessly, and if that would involve having users convert their books (either manually or through automation) until an "on the fly" conversion is available, I would argue that would be better. Otherwise no one is pushed to improve things as they "kinda work well enough" and the users experience an "imperfect" solution.

i.e. if only `kepub`s will be allowed through on the sync, users will have a perfect experiene once they start converting books, and eventually there will be a better automation to do this if we set the experience bar this high

Just my 0.02EUR ;)

**Comment by dmogle** [comment]
Hm, I get where you're coming from. On the other hand, folks who are currently using this feature might see large chunks of their library disappear from the Sync API. Maybe we should wait to see if others chime in?

**Comment by flying-sausages** [comment]
Yeah this should be handled with care, I agree.

**Comment by robandstuff** [comment]
I think that the risk of having users libraries suddenly be missing from the Sync API outweighs the chance to implement a "perfect" solution. Giving users a slightly better experience now and continuing to work towards an automated conversion seems like a win-win solution.

**Comment by flying-sausages** [comment]
FWIW, In my own pursuit to achieve a 100% kepub library, I've gone and made this script. It's not perfect, but it's mine. https://gist.github.com/flying-sausages/2684b07e326a17f7245ca3f1812376ef

**Comment by dmogle** [comment]
Thanks for posting your script, I was struggling to do something similar!

**Review by flying-sausages — APPROVED** [review]
tested and working

**Comment by flying-sausages** [comment]
> tested and working

I might have to retract that later, I'm getting a lot of "Sync failed" on my Forma. I'm hoping it's something to do with Wi-Fi and not the simple change above. Will come back to this tomorrow.

**Comment by flying-sausages** [comment]
> > tested and working
> 
> I might have to retract that later

Never mind, a factory reset fixed it all. It's working great.

**Comment by flying-sausages** [comment]
@dmogle Been using this in my "prod" and so far so good. Just wanted to give you a headsup that my script had a pretty glaring flaw so all kepubs were just copies. I updated the script and added a script to find the affected books so you can find them too.

**Comment by LordSushiPhoenix** [comment]
I merged this into the docker container I'm using the other day and it is working well. Books that only have epub available are downloaded as "fake kepub" and exhibit the issues that come with that, but any books that have kepub available download as proper kepubs. 

I have not tried using a script to convert all my books to kepub, just converting them as I either add new books or notice issues with previously added ones. When I notice issues, removing the download on my ereader, converting to kepub in the webui, and re-downloading is enough to get the proper kepub.

**Comment by OzzieIsaacs** [comment]
Thanks for point out the problem. I found out that kobo's favorite format is epub3 format, so I just send the kepub link for epub3 format

**Comment by OzzieIsaacs** [comment]
Okay, I see the problem

**Comment by adamcstephens** [comment]
I bulk converted all my books with calibre, and this patch definitely fixes the problems associated with kobo syncing.

Looking forward to a new release so that the downstream docker containers get this fix.

Thanks for the fix!

**Pull request merged**
