### PR TITLE
Other docker containers

### PR DESCRIPTION
**Pull request by CHBMB**
Wondered if you'd mind adding a bit about our containers to the readme, might be nice for people using other architectures.

### CODE REVIEW

**Comment by saitoh183** [comment]
@CHBMB 

do the other containers support google drive configuration? Meaning the necessary folders are exposed as volumes?

**Comment by CHBMB** [comment]
@saitoh183 

Not at the moment.  I think there might be some issues with gdrive implementation at the moment.  Never really used it myself, but playing around with it tonight I'm struggling to get very far, although your issue reports were helpful! :wink:

**Comment by saitoh183** [comment]
@CHBMB yeah with the current release changes to the Gdrive integration, I couldn't get it to work. So I decided to go the unionfs+plexdrive method. But it would be good to still have the configuration possible once the Bugs are fixed

**Comment by CHBMB** [comment]
@saitoh183 Yeah, I agree, got no problem implementing it once the issues are ironed out.

**Pull request merged**
