### PR TITLE
Restrict a user to a set of tags

### PR DESCRIPTION
**Pull request by tomjmul**
Provides the ability to restrict the user's view to books having a configurable set of tags

Screenshot 2019-03-19 at 13 35 50

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
Thanks for the PR. 
I'd prefer to have only one field in the database for limiting the visibility. We could have something like +tagname, -tagname for excluding and including tags
I'm fine with 2 fields for the user interface (for now), including #800 will have additional impact.

**Comment by tomjmul** [comment]
Understood. I'm afraid I'm not accomplished enough with Python to do that within the time I could devote to it. Feel free to close the PR.

**Comment by OzzieIsaacs** [comment]
I'll take the PR and will improve it towards the final version

**Comment by Gentleman03** [comment]
How work is going with this featuer? It would be fantastic to have it.

**Comment by OzzieIsaacs** [comment]
It's implemented, I currently writing tests for it. I think within this month we will see it in the master branch

**Comment by Gentleman03** [comment]
That is great! Thank you for your work <3

**Comment by tomjmul** [comment]
@OzzieIsaacs very nicely implemented. Thanks for all your hard work on this project.

**Pull request merged**
