### PR TITLE
[Feature request] magic login link QR code #781

### PR DESCRIPTION
**Pull request by coissac**
A proposition to implement the feature request #781 asking for a QR code on the magic login link page.
As proposed, the solution is based on the `qrcode` python library and consists of modifications to two files:

- `cps/remotelogin.py`: add code into the `remote_login()` function and imports conditionally the `qrcode` library
-  `cps/templates/remote_login.html`: change the template to display, if available, the QR code below the original link

The two other modified files are only to declare the dependency to the `qrcode` library 

All the best

Eric

### CODE REVIEW

**Comment by OzzieIsaacs** [comment]
I see in the linked issue that I agreed at that time to implement the feature. 
5 years have passed since then and I've become a lot wiser. I now have a contributing file and there I explained that I will not add another login method. I consider this an additional login method.
I added up a lot of stuff in the past 5 year and some of it creates constantly trouble and don't want to have any more "non book related" issues. 

So I'm sorry, but I will not merge it.

**Comment by coissac** [comment]
Five years ago, I did not use your soft.
No problem for me if you didn't want to merge. I have my fork, which I'm now using as my reference version for my server. I just wanted to help your project. But you are the boss of your repository.

Cheers.

**Comment by OzzieIsaacs** [comment]
Thanks for the effort you put into it. Feel free to fork the software and use it as it fits best to your beeds

**Comment by gelbphoenix** [comment]
Sorry for commenting on a rejected pull request. But as a question: 

Isn't this more a UI change than a new login method? 

The Magic Link login method (which is opt-in) already existed before this PR and this PR would only add the possibility to show an QR code with the already existing magic link. This would enable that a user could use their smartphone or tablet to easily authenticate their e-reader.

**Comment by coissac** [comment]
Perfectly agree.
But it's normal than @OzzieIsaacs manages his project as he wishes ;-)

All the best

**Comment by gelbphoenix** [comment]
@coissac Maybe you could make this PR for https://github.com/crocodilestick/Calibre-Web-Automated?

**Comment by coissac** [comment]
I was not aware about this project, I'll think about as soon as I've finished some duties for my main job ;-)

**Pull request closed without merging**
