### PR TITLE
Save progress to database on every page change in epub reader

### PR DESCRIPTION
**Pull request by dydyamotya**
Hello!

My girlfriend wants to read the book both on her smartphone and laptop, and she wants it to be synchronized between both devices. So, I made this addition to online epub reader.

I also saw a couple of requests for feature before on the net, so this could be popular improvement.

Please check if it is ok for the project. 

Thank you for your attention.

### CODE REVIEW

**Review by sk4rd — APPROVED** [review]

**Comment by 1447262390** [comment]
This feature is very useful, thank you

**Comment by linonetwo** [comment]
will this work for txt? #2946

**Comment by Zwixx** [comment]
> will this work for txt? #2946

No, it only works with epub

**Comment by OzzieIsaacs** [comment]
I don't think this is good idea, as it creates a lot of write actions on the database (I will also revert this for the comic reader)

**Pull request closed without merging**
