### PR TITLE
Feature: Added basic theming to the epub reader

### LINKED ISSUE #1960: Dark mode/themes for epub reader
**Is your feature request related to a problem? Please describe.**
My eyes burn when reading using the epub reader (epub.js) in the dark.

**Describe the solution you'd like**
Option to change themes in the epub reader.

**Describe alternatives you've considered**
I was thinking about trying to do this myself, but as I have next to no experience in contributing to projects and am still a noob coder so I figured I should just make a feature request. I'll still probably try.

**Additional context**
Some people have already tried this. Here are some helpful links to those Issues:
https://github.com/janeczku/calibre-web/issues/778#issuecomment-456560756
https://github.com/janeczku/calibre-web/pull/1736
https://github.com/janeczku/calibre-web/pull/1796

### PR DESCRIPTION
**Pull request by bharatknv**
I added a sepia and dark theme to the epub reader. You can select the theme in the settings tab.
Fixes #1960

### CODE REVIEW

**Comment by JoeMamaAME** [comment]
Very cool, manually applied the code to my installation. A dark gray theme would be nice, black is a bit harsh to me.

**Comment by pastorjack** [comment]
I would love this so much! I need a dark theme

**Comment by EienFr** [comment]
> I added a sepia and dark theme to the epub reader. You can select the theme in the settings tab. Fixes #1960

Try to apply your fix but the text color never change (white for dark theme. It's still black).

**Comment by EienFr** [comment]
> Very cool, manually applied the code to my installation. A dark gray theme would be nice, black is a bit harsh to me.

@JoeMamaAME : Change in read.html these lines 

            if (id == "darkTheme") {
              document.getElementById("main").style.backgroundColor = "**black**";
            }

Put a grey hex color instead of black

**Comment by bharatknv** [comment]
> Very cool, manually applied the code to my installation. A dark gray theme would be nice, black is a bit harsh to me.

Sure, I'll change the dark theme to be dark gray and add a separate black theme. Or you could do what @EienFr suggested if that would be faster for you

**Comment by bharatknv** [comment]
> > I added a sepia and dark theme to the epub reader. You can select the theme in the settings tab. Fixes #1960
> 
> @bharatknv : I try to apply your fix but the text color never change (white for dark theme. It's still black).

It is working for me. Could you please send a screenshot?

**Pull request merged**
