### PR TITLE
Feature: read epub in Honkit&Gitbook website style

### PR DESCRIPTION
**Pull request by jim3ma**
Calibre uses epub.js to read book online, but I like the  experience which [Honkit](https://github.com/honkit/honkit)&gitbook website style, like: 

I have created a repo https://github.com/jim3ma/epub2website which can convert epub to a gitbook style website. I have extended it in calibre web.

The document about how to use it with calibre web is here: https://github.com/jim3ma/epub2website#integration-with-calibre-web

### CODE REVIEW

**Review by kelvinalfaro — APPROVED** [review]

**Comment by jim3ma** [comment]
@kelvinalfaro Can you merge this PR ?

**Comment by jim3ma** [comment]
CC @OzzieIsaacs

**Comment by yutotakano** [comment]
I'd love to see this, hope it gets merged soon!

**Comment by OzzieIsaacs** [comment]
Sorry, we have one epub reader, I will not add another one, I barely can support what we have currently

**Pull request closed without merging**
